Traceback (most recent call last):
  File "/home/thierryys/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/thierryys/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/thierryys/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/thierryys/anaconda3/envs/jupyterbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/thierryys/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/thierryys/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thierryys/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

# Load the dataset
file_path = r"C:\Users\jensb\Documents\Kunstmatige Intelligentie\Info Vis\Infovis_2024\Environment_Temperature_change_E_All_Data_NOFLAG.csv"
df = pd.read_csv(file_path, sep=",", encoding='latin1', on_bad_lines='skip', low_memory=False)

# Display the first few rows to understand the structure
print(df.head())

# Aggregate data by country and year
# We will focus on the 'Temperature change' element
temperature_df = df[df['Element'] == 'Temperature change']

# Melt the dataframe to have years as a single column
temperature_melted = temperature_df.melt(
    id_vars=['Area'],
    value_vars=[col for col in temperature_df.columns if col.startswith('Y')],
    var_name='Year',
    value_name='TemperatureChange'
)

# Clean up the year column
temperature_melted['Year'] = temperature_melted['Year'].str[1:]

# Display the aggregated data
print(temperature_melted.head())

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      3[0m [38;5;66;03m# Load the dataset[39;00m
[1;32m      4[0m file_path [38;5;241m=[39m [38;5;124mr[39m[38;5;124m"[39m[38;5;124mC:[39m[38;5;124m\[39m[38;5;124mUsers[39m[38;5;124m\[39m[38;5;124mjensb[39m[38;5;124m\[39m[38;5;124mDocuments[39m[38;5;124m\[39m[38;5;124mKunstmatige Intelligentie[39m[38;5;124m\[39m[38;5;124mInfo Vis[39m[38;5;124m\[39m[38;5;124mInfovis_2024[39m[38;5;124m\[39m[38;5;124mEnvironment_Temperature_change_E_All_Data_NOFLAG.csv[39m[38;5;124m"[39m

[0;31mModuleNotFoundError[0m: No module named 'pandas'

